version: "3.7"

services:
  mycroft:
    image: mycroftai/docker-mycroft
    environment:
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
    ports:
      - "8181:8181"
    volumes:
      - ".:/root/.mycroft"
      - "${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native"
      - "${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie"
    devices:
      - "/dev/snd"
